language:
  - cpp
  - python
python:
  - "2.7"
  - "3.3"
compiler:
  - gcc
notifications:
  email: false
env:
  - ROS_DISTRO=hydro ROSWS=wstool BUILDER=catkin USE_DEB=true
  - ROS_DISTRO=hydro ROSWS=wstool BUILDER=catkin USE_DEB=false
  - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin USE_DEB=true
  - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin USE_DEB=false
matrix:
  allow_failures:
    - ROS_DISTRO=hydro ROSWS=wstool BUILDER=catkin USE_DEB=true
    - ROS_DISTRO=hydro ROSWS=wstool BUILDER=catkin USE_DEB=false
    - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin USE_DEB=true
    - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin USE_DEB=false
cache:
  apt: true
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export ROS_DISTRO=hydro
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
#  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool
#  - sudo apt-get install -qq -y ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros ros-$ROS_DISTRO-ros-base
#  - sudo apt-get install -qq -y ros-$ROS_DISTRO-cv-bridge ros-$ROS_DISTRO-image-transport ros-$ROS_DISTRO-pcl-ros
#  - sudo apt-get install -qq -y ros-$ROS_DISTRO-sensor-msgs
  - sudo apt-get install -qq -y libopencv-dev
  - sudo apt-get install -qq -y libpcl-1.7-all-dev
  # Setup rosdep
  - sudo rosdep init
  - rosdep update
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source /opt/ros/$ROS_DISTRO/setup.bash
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - make driver logic decision
