language:
  - cpp
  - python
python:
  - "2.7"
  - "3.3"
compiler:
  - gcc
notifications:
  email: false
cache:
  apt: true
  directories:
  - ros_catkin_ws
env:
  - ROS_DISTRO=indogo ROSWS=wstool BUILDER=catkin
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libopencv-dev
  - sudo apt-get install -qq -y libpcl-1.7-all-dev
  - sudo apt-get install -qq -y libboost-program-options-dev
  - bash -x .travis/compile_indigo.bash
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source ros_catkin_ws/install_isolated/setup.bash
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - make driver logic decision
