language:
  - cpp
  - python
python:
  - "2.7"
  - "3.3"
compiler:
  - gcc
notifications:
  email: false
cache:
  apt: true
  pip: true
  directories:
  - $HOME/ros_catkin_ws
  - $HOME/cv
  - $HOME/boost
env:
  - ROS_DISTRO=indigo ROSWS=wstool BUILDER=catkin
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - bash -x .travis/apt_install.bash
  - bash -x .travis/install_cv.bash
  - bash -x .travis/console_bridge.bash
  #- bash -x .travis/build_catkin.bash
  - bash -x .travis/compile_indigo.bash
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - cd $HOME
  - source ros_catkin_ws/install_isolated/setup.bash
  - cd $CI_SOURCE_PATH
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - make downloaded
  - rospack profile
  - make driver logic decision
